# This viminfo file was generated by Vim 7.2.
# You may edit it if you're careful!

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~H
# Last Search Pattern:
~MSle0~/ws

# Last Substitute String:
$

# Command Line History (newest to oldest):
:wq
:q
:w
:Wq
:Q
:e! ~/bitstamp-recorder/retart-bitstamp-recorder.sh
:e ~/bitstamp-recorder/retart-bitstamp-recorder.sh
:w ~/bitstamp-recorder/retart-bitstamp-recorder.sh
:e ~/mtgox-recorder/bash-scripts/restart-mtgox-recorder.sh
:e ~/bitstamp-recorder/stop-bitstamp-recorder.sh
:w ~/bitstamp-recorder/stop-bitstamp-recorder.sh
:e ~/mtgox-recorder/bash-scripts/kill-mtgox-recorder.sh
:e start-bitstamp-recorder.sh
:e monitor-bitstamp-recorder.sh
:e ~/bitstamp-recorder/is-bitstamp-recorder-running.sh
:w ~/bitstamp-recorder/is-bitstamp-recorder-running.sh
:e ~/mtgox-recorder/bash-scripts/is-mtgox-recorder-running.sh
:w ~/bitstamp-recorder/monitor-bitstamp-recorder.sh
:e ~/mtgox-recorder/bash-scripts/monitor-mtgox-recorder.sh
:w ~/bitstamp-recorder/start-bitstamp-recorder.sh
:e ~/mtgox-recorder/bash-scripts/start-mtgox-recorder.sh
:vsp
:!z
:e ~/mtgox-recorder/mtgox-recorder.py
:e ~/bitstamp-recorder/2014-05-02_11h42h20s_bitstamp_data.csv
:e ../mtgox-recorder/mtgox-recorder.py
:q!
:e bash-scripts/restart-mtgox-recorder.sh
:e bash-scripts/monitor-mtgox-recorder.sh
:e bash-scripts/
:e bash-scripts/start-mtgox-recorder.sh
:sp
:resize -10
:set wrap!
:s
:!
:W
:e
:e ws_data_2.txt
:set wrap
:set number
:set wrp!

# Search String History (newest to oldest):
?/ws
?/ws_
? \<This\>
? ^\d\{3}ÿ
?/Jan 1 00:46
?/Jan 01 00
?/"633.26061"
?/"1387730977135781"

# Expression History (newest to oldest):

# Input Line History (newest to oldest):

# Input Line History (newest to oldest):

# Registers:
"0	LINE	0
	with open('2014-05-07_16h15h40s_bitstamp_data.csv', 'r') as f:
		print(f.closed)
	print(f.closed)
""1	LINE	0
	
"2	LINE	0
	" set background=dark
	" let g:solarized_termcolors=256
	" colorscheme solarized
"3	LINE	0
	
"4	LINE	0
	
"5	LINE	0
	alias ps="ps -f -u dima"
"6	LINE	0
	alias ll="ls -hl"
"7	LINE	0
	# User specific aliases and functions
	export TERM=xterm-256color
	eval `dircolors ~/dircolors-solarized/dircolors.ansi-dark`
"8	LINE	0
	
"9	LINE	0
	#export PS1="\[\e[00;35m\]\H\[\e[0m\]\[\e[00;37m\]:\w$ \[\e[0m\]"
"-	CHAR	0
	-

# File marks:
'0  1  0  ~/.vimrc
'1  5  0  ~/.vimrc
'2  5  1  ~/.vimrc
'3  1  0  ~/bash-scripts/.bash_profile
'4  4  0  ~/.bashrc
'5  4  18  ~/.vimrc
'6  5  0  ~/.bashrc
'7  5  0  ~/.bashrc
'8  5  0  ~/.bashrc
'9  12  20  ~/.bash_profile

# Jumplist (newest first):
-'  1  0  ~/.vimrc
-'  5  0  ~/.vimrc
-'  4  0  ~/.vimrc
-'  1  0  ~/bash-scripts/.bash_profile
-'  4  0  ~/.bashrc
-'  5  0  ~/.bashrc
-'  12  20  ~/.bash_profile
-'  7  11  ~/bitstamp-websocket-recorder/.gitignore
-'  6  0  ~/bitstamp-websocket-recorder/.gitignore
-'  1  0  ~/bitstamp-websocket-recorder/.gitignore
-'  3  67  ~/bitstamp-websocket-recorder/bitstamp.conf
-'  1  0  ~/bitstamp-websocket-recorder/bitstamp.conf
-'  15  0  ~/bash-extravaganza/.bash_profile
-'  14  0  ~/bash-extravaganza/.bash_profile
-'  13  0  ~/.bash_profile
-'  1  0  ~/bash-extravaganza/.bash_profile
-'  48893  0  ~/python-process-statistics.log
-'  52244  0  ~/python-process-statistics.log
-'  34  0  ~/python-process-statistics.log
-'  1  0  ~/python-process-statistics.log
-'  71  0  ~/bitstamp-recorder/bitstamp-websocket-recorder.py
-'  73  0  ~/bitstamp-recorder/bitstamp-websocket-recorder.py
-'  2326  0  ~/bitstamp-recorder/recorder.log
-'  1  0  ~/bitstamp-recorder/recorder.log
-'  3  0  ~/bitstamp-recorder/is-recorder-running.sh
-'  53  3  ~/bitstamp-recorder/bitstamp-websocket-recorder.py
-'  9  0  ~/bitstamp-recorder/start-recorder.sh
-'  23  0  ~/bitstamp-recorder/restart-recorder.sh
-'  17  0  ~/bitstamp-recorder/restart-recorder.sh
-'  1  0  ~/bitstamp-recorder/restart-recorder.sh
-'  7  0  ~/bitstamp-recorder/stop-recorder.sh
-'  1  0  ~/bitstamp-recorder/stop-recorder.sh
-'  1  0  ~/bitstamp-recorder/start-recorder.sh
-'  8  109  ~/bitstamp-recorder/start-recorder.sh
-'  23  24  ~/bitstamp-recorder/restart-bitstamp-recorder.sh
-'  12  21  ~/bitstamp-recorder/monitor-recorder.sh
-'  1  0  ~/bitstamp-recorder/monitor-recorder.sh
-'  1  0  ~/bitstamp-recorder/is-recorder-running.sh
-'  17  136  ~/bitstamp-recorder/monitor-bitstamp-recorder.sh
-'  10  1  ~/bitstamp-recorder/monitor-bitstamp-recorder.sh
-'  4  7  ~/bitstamp-recorder/.gitignore
-'  3  0  ~/bitstamp-recorder/.gitignore
-'  1  0  ~/bitstamp-recorder/.gitignore
-'  1  0  ~/bitstamp-recorder/bitstamp-websocket-recorder.py
-'  53  3  ~/bitstamp-recorder/bitstamp-recorder.py
-'  72  0  ~/bitstamp-recorder/bitstamp-recorder.py
-'  15  5  ~/bitstamp-recorder/bitstamp-recorder.py
-'  12  32  ~/bitstamp-recorder/bitstamp-recorder.py
-'  66  50  ~/bitstamp-recorder/bitstamp-recorder.py
-'  13  0  ~/bitstamp-recorder/bitstamp-recorder.py
-'  1  0  ~/bitstamp-recorder/bitstamp-recorder.py
-'  46  0  ~/bitstamp-recorder/bitstamp-recorder.py
-'  1  0  ~/.ssh/authorized_keys
-'  1  0  ~/.bash_profile
-'  1  0  ~/.bashrc
-'  3150  0  ~/bitstamp-recorder/bitstamp-recorder.log
-'  3149  0  ~/bitstamp-recorder/bitstamp-recorder.log
-'  1  0  ~/bitstamp-recorder/bitstamp-recorder.log
-'  21  0  ~/bitstamp-recorder/bitstamp-recorder.py
-'  35  32  ~/bitstamp-recorder/test/is-file-open.py
-'  33  3  ~/bitstamp-recorder/test/is-file-open.py
-'  36  3  ~/bitstamp-recorder/test/is-file-open.py
-'  37  0  ~/bitstamp-recorder/test/is-file-open.py
-'  1  0  ~/bitstamp-recorder/test/is-file-open.py
-'  31  17  ~/bitstamp-recorder/is-file-open.py
-'  5  0  ~/bitstamp-recorder/is-file-open.py
-'  27  1  ~/bitstamp-recorder/is-file-open.py
-'  28  1  ~/bitstamp-recorder/is-file-open.py
-'  32  0  ~/bitstamp-recorder/is-file-open.py
-'  24  0  ~/bitstamp-recorder/is-file-open.py
-'  19  1  ~/bitstamp-recorder/is-file-open.py
-'  21  3  ~/bitstamp-recorder/is-file-open.py
-'  1  0  ~/bitstamp-recorder/is-file-open.py
-'  18  1  ~/bitstamp-recorder/is-file-open.py
-'  4  69  ~/bitstamp-recorder/is-bitstamp-recorder-running.sh
-'  18  0  ~/bitstamp-recorder/monitor-bitstamp-recorder.sh
-'  11  1  ~/bitstamp-recorder/monitor-bitstamp-recorder.sh
-'  5  10  ~/bitstamp-recorder/test.sh
-'  1  0  ~/bitstamp-recorder/test.sh
-'  12  1  ~/bitstamp-recorder/monitor-bitstamp-recorder.sh
-'  13  1  ~/bitstamp-recorder/monitor-bitstamp-recorder.sh
-'  34  9  ~/bitstamp-recorder/is-file-open.py
-'  51  2  ~/bitstamp-recorder/bitstamp-recorder.py
-'  1  110  ~/bitstamp-recorder/2014-05-07_16h15h40s_bitstamp_data.csv
-'  11  77  ~/bitstamp-recorder/monitor-mtgox-recorder.sh
-'  1  0  ~/bitstamp-recorder/monitor-mtgox-recorder.sh
-'  18  0  ~/bitstamp-recorder/restart-bitstamp-recorder.sh
-'  8  0  ~/bitstamp-recorder/stop-bitstamp-recorder.sh
-'  12  0  ~/bitstamp-recorder/restart-bitstamp-recorder.sh
-'  1  0  ~/bitstamp-recorder/restart-bitstamp-recorder.sh
-'  7  0  ~/bitstamp-recorder/start-bitstamp-recorder.sh
-'  7  0  ~/bitstamp-recorder/stop-bitstamp-recorder.sh
-'  50  2  ~/bitstamp-recorder/bitstamp-recorder.py
-'  16  0  ~/bitstamp-recorder/monitor-bitstamp-recorder.sh
-'  9  0  ~/bitstamp-recorder/stop-bitstamp-recorder.sh
-'  1  0  ~/bitstamp-recorder/is-bitstamp-recorder-running.sh
-'  54  0  ~/bitstamp-recorder/bitstamp-recorder.py

# History of marks within files (newest to oldest):

> ~/.vimrc
	"	1	0
	^	1	12
	.	1	11
	+	4	0
	+	5	1
	+	5	1
	+	5	1
	+	5	0
	+	5	0
	+	5	0
	+	2	0
	+	1	11

> ~/bash-scripts/.bash_profile
	"	1	0

> ~/.bashrc
	"	4	0
	.	5	0
	+	5	1
	+	1	0
	+	5	0
	+	5	0
	+	5	0
	+	5	0
	+	5	0

> ~/.bash_profile
	"	12	20
	^	12	21
	.	12	20
	+	13	0
	+	12	20

> ~/bitstamp-websocket-recorder/.gitignore
	"	7	11
	^	7	12
	.	7	11
	+	6	12
	+	7	11

> ~/bitstamp-websocket-recorder/bitstamp.conf
	"	3	67
	^	3	68
	.	3	67
	+	15	27
	+	3	67

> ~/bash-extravaganza/.bash_profile
	"	15	0
	^	15	157
	.	15	0
	+	15	152
	+	15	153
	+	15	0

> ~/python-process-statistics.log
	"	48893	0

> ~/bitstamp-recorder/bitstamp-websocket-recorder.py
	"	71	0
	^	21	28
	.	21	27
	+	54	0
	+	53	94
	+	20	27
	+	21	27

> ~/bitstamp-recorder/recorder.log
	"	2326	0

> ~/bitstamp-recorder/is-recorder-running.sh
	"	3	0
	^	3	65
	.	3	65
	+	4	40
	+	3	65

> ~/bitstamp-recorder/start-recorder.sh
	"	9	0
	^	3	36
	.	10	0
	+	8	16
	+	9	23
	+	8	109
	+	4	18
	+	8	0
	+	4	41
	+	3	56
	+	6	98
	+	8	0
	+	8	39
	+	2	53
	+	2	53
	+	3	35
	+	10	0

> ~/bitstamp-recorder/restart-recorder.sh
	"	23	0
	^	23	24
	.	23	24
	+	23	129
	+	23	24

> ~/bitstamp-recorder/stop-recorder.sh
	"	7	0
	^	7	136
	.	8	0
	+	4	47
	+	5	31
	+	7	136
	+	8	0

> ~/bitstamp-recorder/restart-bitstamp-recorder.sh
	"	23	24
	^	23	25
	.	23	24
	+	23	160
	+	16	26
	+	12	59
	+	3	41
	+	23	24

> ~/bitstamp-recorder/monitor-recorder.sh
	"	12	21
	.	9	28
	+	9	28

> ~/bitstamp-recorder/monitor-bitstamp-recorder.sh
	"	17	136
	^	17	137
	.	17	50
	+	17	117
	+	17	14
	+	10	1
	+	11	0
	+	10	41
	+	11	64
	+	12	89
	+	11	21
	+	8	0
	+	18	3
	+	5	75
	+	6	69
	+	12	76
	+	11	46
	+	17	50

> ~/bitstamp-recorder/.gitignore
	"	4	7
	^	4	8
	.	4	7
	+	3	3
	+	2	1
	+	3	1
	+	6	0
	+	5	4
	+	4	7

> ~/bitstamp-recorder/bitstamp-recorder.py
	"	53	3
	^	53	7
	.	53	6
	+	31	16
	+	33	0
	+	32	1
	+	31	95
	+	17	0
	+	22	0
	+	12	30
	+	9	59
	+	2	94
	+	9	93
	+	9	171
	+	10	143
	+	10	143
	+	10	142
	+	4	17
	+	2	95
	+	3	92
	+	5	0
	+	6	114
	+	9	78
	+	9	100
	+	12	30
	+	10	81
	+	12	0
	+	10	0
	+	12	30
	+	12	30
	+	12	62
	+	13	0
	+	14	0
	+	12	1
	+	10	1
	+	9	1
	+	7	1
	+	6	1
	+	4	4
	+	2	1
	+	3	1
	+	4	1
	+	5	0
	+	8	0
	+	11	0
	+	24	66
	+	24	123
	+	24	100
	+	27	40
	+	38	52
	+	43	8
	+	48	70
	+	48	69
	+	48	70
	+	50	0
	+	51	2
	+	54	0
	+	71	0
	+	54	0
	+	51	35
	+	47	110
	+	48	63
	+	48	69
	+	48	108
	+	49	44
	+	50	124
	+	21	46
	+	21	0
	+	21	0
	+	19	0
	+	20	37
	+	21	18
	+	20	24
	+	21	24
	+	20	40
	+	21	40
	+	20	36
	+	21	42
	+	43	21
	+	43	130
	+	54	0
	+	45	0
	+	44	1
	+	43	12
	+	44	2
	+	45	16
	+	50	2
	+	51	62
	+	53	6

> ~/.ssh/authorized_keys
	"	1	0
